{
 "title": "MANDATORIO — Loki logs",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requisições em available-schedules-go",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=\"available-schedules-go\"} |~ `500` [5m]))",
     "legendFormat": "COD 500"
    },
    {
     "expr": "sum by(app) (count_over_time({app=\"available-schedules-go\"} |~ `200` [5m]))",
     "legendFormat": "COD 200"
    }
   ]
  },
  {
   "title": "Erro em % - available-schedules-go",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "100 * (sum(count_over_time({app=\"available-schedules-go\"} |~ `500` [5m]))/sum(count_over_time({app=\"available-schedules-go\"} [5m])))",
     "legendFormat": "Erro (%)"
    }
   ]
  },
  {
   "title": "Requisições em available-schedules-python",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=\"available-schedules-python\"} |~ `500` [5m]))",
     "legendFormat": "COD 500"
    },
    {
     "expr": "sum by(app) (count_over_time({app=\"available-schedules-python\"} |~ `200` [5m]))",
     "legendFormat": "COD 200"
    }
   ]
  },
  {
   "title": "Erro em % - available-schedules-python",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "100 * (sum(count_over_time({app=\"available-schedules-python\"} |~ `500` [5m]))/sum(count_over_time({app=\"available-schedules-python\"} [5m])))",
     "legendFormat": "Erro (%)"
    }
   ]
  },
  {
   "title": "Logs de Erro 500",
   "type": "logs",
   "gridPos": { "x": 0, "y": 14, "h": 8, "w": 23 },
   "targets": [
    {
     "expr": "{app=~\"available-schedules-go|available-schedules-python\"} |~ `500 Internal Server Error`",
     "direction": "backward"
    }
   ]
  }
 ]
}